// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IAnsiRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Ansi entity.</summary>
    public interface IAnsiRepository
    {
        void Add(AnsiRecord ansi);
        void Update(AnsiRecord ansi);
        void Remove(AnsiRecord ansi);
        AnsiRecord GetById(long ansiId);
        AnsiRecord GetByName(string name);
        ICollection<AnsiRecord> FetchAll();
    }
}