// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IAreaRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Area entity.</summary>
    public interface IAreaRepository
    {
        void Add(AreaRecord area);
        void Update(AreaRecord area);
        void Remove(AreaRecord area);
        AreaRecord GetById(long areaId);
        AreaRecord GetByName(string name);
        ICollection<AreaRecord> FetchAll();
    }
}