// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IBannedIpAddressRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the BannedIpAddress entity.</summary>
    public interface IBannedIpAddressRepository
    {
        void Add(BannedIpAddressRecord bannedipaddress);
        void Update(BannedIpAddressRecord bannedipaddress);
        void Remove(BannedIpAddressRecord bannedipaddress);
        BannedIpAddressRecord GetById(long bannedipaddressId);
        BannedIpAddressRecord GetByName(string name);
        ICollection<BannedIpAddressRecord> FetchAll();
    }
}