// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IDayNameRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the DayName entity.</summary>
    public interface IDayNameRepository
    {
        void Add(DayNameRecord dayname);
        void Update(DayNameRecord dayname);
        void Remove(DayNameRecord dayname);
        DayNameRecord GetById(long daynameId);
        DayNameRecord GetByName(string name);
        ICollection<DayNameRecord> FetchAll();
    }
}