// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IDoorSideRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the DoorSide entity.summary>
    public interface IDoorSideRepository
    {
        void Add(DoorSideRecord doorside);
        void Update(DoorSideRecord doorside);
        void Remove(DoorSideRecord doorside);
        DoorSideRecord GetById(long doorsideId);
        DoorSideRecord GetByName(string name);
        ICollection<DoorSideRecord> FetchAll();
    }
}