// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IExitRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Exit entity.</summary>
    public interface IExitRepository
    {
        void Add(ExitRecord exit);
        void Update(ExitRecord exit);
        void Remove(ExitRecord exit);
        ExitRecord GetById(long exitId);
        ExitRecord GetByName(string name);
        ICollection<ExitRecord> FetchAll();
    }
}