// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IHelpTopicAliasRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the HelpTopicAlias entity.</summary>
    public interface IHelpTopicAliasRepository
    {
        void Add(HelpTopicAliasRecord helptopicalias);
        void Update(HelpTopicAliasRecord helptopicalias);
        void Remove(HelpTopicAliasRecord helptopicalias);
        HelpTopicAliasRecord GetById(long helptopicaliasId);
        HelpTopicAliasRecord GetByName(string name);
        ICollection<HelpTopicAliasRecord> FetchAll();
    }
}