// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IHelpTopicRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the HelpTopic entity.</summary>
    public interface IHelpTopicRepository
    {
        void Add(HelpTopicRecord helptopic);
        void Update(HelpTopicRecord helptopic);
        void Remove(HelpTopicRecord helptopic);
        HelpTopicRecord GetById(long helptopicId);
        HelpTopicRecord GetByName(string name);
        ICollection<HelpTopicRecord> FetchAll();
    }
}