// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IIacRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Iac entity.</summary>
    public interface IIacRepository
    {
        void Add(IacRecord iac);
        void Update(IacRecord iac);
        void Remove(IacRecord iac);
        IacRecord GetById(long iacId);
        IacRecord GetByName(string name);
        ICollection<IacRecord> FetchAll();
    }
}