// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IMobTypeRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the MobType entity.</summary>
    public interface IMobTypeRepository
    {
        void Add(MobTypeRecord mobtype);
        void Update(MobTypeRecord mobtype);
        void Remove(MobTypeRecord mobtype);
        MobTypeRecord GetById(long mobtypeId);
        MobTypeRecord GetByName(string name);
        ICollection<MobTypeRecord> FetchAll();
    }
}