// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IMudChannelRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the MudChannel entity.</summary>
    public interface IMudChannelRepository
    {
        void Add(MudChannelRecord mudchannel);
        void Update(MudChannelRecord mudchannel);
        void Remove(MudChannelRecord mudchannel);
        MudChannelRecord GetById(long mudchannelId);
        MudChannelRecord GetByName(string name);
        ICollection<MudChannelRecord> FetchAll();
    }
}