// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IPlayerRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Player entity.</summary>
    public interface IPlayerRepository
    {
        void Add(PlayerRecord player);
        void Update(PlayerRecord player);
        void Remove(PlayerRecord player);
        PlayerRecord GetById(long playerId);
        PlayerRecord GetByName(string name);
        ICollection<PlayerRecord> FetchAll();
    }
}