// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IPlayerChannelRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the PlayerChannel entity.</summary>
    public interface IPlayerChannelRepository
    {
        void Add(PlayerChannelRecord playerchannel);
        void Update(PlayerChannelRecord playerchannel);
        void Remove(PlayerChannelRecord playerchannel);
        PlayerChannelRecord GetById(long playerchannelId);
        PlayerChannelRecord GetByName(string name);
        ICollection<PlayerChannelRecord> FetchAll();
    }
}