// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IPortalExitRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the PortalExit entity.</summary>
    public interface IPortalExitRepository
    {
        void Add(PortalExitRecord portalexit);
        void Update(PortalExitRecord portalexit);
        void Remove(PortalExitRecord portalexit);
        PortalExitRecord GetById(long portalexitId);
        PortalExitRecord GetByName(string name);
        ICollection<PortalExitRecord> FetchAll();
    }
}