// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IRoomRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Room entity.</summary>
    public interface IRoomRepository
    {
        void Add(RoomRecord room);
        void Update(RoomRecord room);
        void Remove(RoomRecord room);
        RoomRecord GetById(long roomId);
        RoomRecord GetByName(string name);
        ICollection<RoomRecord> FetchAll();
    }
}