// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="ITypoRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by RepositoryInterface.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System.Collections.Generic;

    /// <summary>Repository interface for the Typo entity.</summary>
    public interface ITypoRepository
    {
        void Add(TypoRecord typo);
        void Update(TypoRecord typo);
        void Remove(TypoRecord typo);
        TypoRecord GetById(long typoId);
        TypoRecord GetByName(string name);
        ICollection<TypoRecord> FetchAll();
    }
}