// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="AnsiRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single ANSI row in the ANSI table.</summary>
    [Alias("ANSI")]
    public partial class AnsiRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual string EscapeCode { get; set; }
        public virtual string Tag { get; set; }
    }
}