// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="AreaRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    /// <summary>Represents a single Area row in the Area table.</summary>
    public partial class AreaRecord
    {
        public virtual long ID { get; set; }
        public virtual string UID { get; set; }
        public virtual string Name { get; set; }
    }
}