// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="BannedIpAddressRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System;
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single BannedIPAddress row in the BannedIPAddress table.</summary>
    [Alias("BannedIPAddresses")]
    public partial class BannedIpAddressRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual string StartIPAddress { get; set; }
        public virtual string EndIPAddress { get; set; }
        public virtual string Note { get; set; }
        public virtual long BannedByPlayerID { get; set; }
        public virtual DateTime BannedDateTime { get; set; }
    }
}