// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MobRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:10 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using System;
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single Mob row in the Mob table.</summary>
    [Alias("Mobs")]
    public partial class MobRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual int MobTypeID { get; set; }
        public virtual string Name { get; set; }
        public virtual string Title { get; set; }
        public virtual string Description { get; set; }
        public virtual int Age { get; set; }
        public virtual int CurrentRoomID { get; set; }
        public virtual string Prompt { get; set; }
        public virtual DateTime CreateDate { get; set; }
    }
}