// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MobTypeRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single MobType row in the MobType table.</summary>
    [Alias("MobTypes")]
    public partial class MobTypeRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual string MobTypeName { get; set; }
    }
}