// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MudChannelRoleRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single MudChannelRole row in the MudChannelRole table.</summary>
    [Alias("MudChannelRoles")]
    public partial class MudChannelRoleRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual long MudChannelID { get; set; }
        public virtual long RoleID { get; set; }
    }
}