// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MxpRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single MXP row in the MXP table.</summary>
    [Alias("MXP")]
    public partial class MxpRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual string ElementName { get; set; }
        public virtual string ElementDefinition { get; set; }
    }
}