// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="RoomTypeRecord.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by EntityRecord.cst on 7/7/2012 4:24:09 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Entities
{
    using ServiceStack.DataAnnotations;

    /// <summary>Represents a single RoomType row in the RoomType table.</summary>
    [Alias("RoomTypes")]
    public partial class RoomTypeRecord
    {
        [AutoIncrement]
        public virtual long ID { get; set; }
        public virtual string Name { get; set; }
        public virtual string Description { get; set; }
    }
}