// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="AnsiRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the ANSI table.</summary>
    public partial class AnsiRepository : IAnsiRepository
    {
        public void Add(AnsiRecord ansi)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(ansi);
                transaction.Commit();
            }
        }

        public void Update(AnsiRecord ansi)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(ansi);
                transaction.Commit();
            }
        }

        public void Remove(AnsiRecord ansi)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(ansi);
                transaction.Commit();
            }
        }

        public AnsiRecord GetById(long ansiId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<AnsiRecord>("ID = {0}", ansiId);
        }

        public AnsiRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<AnsiRecord>("Name = {0}", name);
            }
        }

        public ICollection<AnsiRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<AnsiRecord>();
            }
        }
    }
}