// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="AreaRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the Areas table.</summary>
    public partial class AreaRepository : IAreaRepository
    {
        public void Add(AreaRecord area)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(area);
                transaction.Commit();
            }
        }

        public void Update(AreaRecord area)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(area);
                transaction.Commit();
            }
        }

        public void Remove(AreaRecord area)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(area);
                transaction.Commit();
            }
        }

        public AreaRecord GetById(long areaId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<AreaRecord>("ID = {0}", areaId);
        }

        public AreaRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<AreaRecord>("Name = {0}", name);
            }
        }

        public ICollection<AreaRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<AreaRecord>();
            }
        }
    }
}