// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="BannedIpAddressRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the BannedIPAddresses table.</summary>
    public partial class BannedIpAddressRepository : IBannedIpAddressRepository
    {
        public void Add(BannedIpAddressRecord bannedipaddress)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(bannedipaddress);
                transaction.Commit();
            }
        }

        public void Update(BannedIpAddressRecord bannedipaddress)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(bannedipaddress);
                transaction.Commit();
            }
        }

        public void Remove(BannedIpAddressRecord bannedipaddress)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(bannedipaddress);
                transaction.Commit();
            }
        }

        public BannedIpAddressRecord GetById(long bannedipaddressId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<BannedIpAddressRecord>("ID = {0}", bannedipaddressId);
        }

        public BannedIpAddressRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<BannedIpAddressRecord>("Name = {0}", name);
            }
        }

        public ICollection<BannedIpAddressRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<BannedIpAddressRecord>();
            }
        }
    }
}