// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="DayNameRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the DayNames table.</summary>
    public partial class DayNameRepository : IDayNameRepository
    {
        public void Add(DayNameRecord dayname)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(dayname);
                transaction.Commit();
            }
        }

        public void Update(DayNameRecord dayname)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(dayname);
                transaction.Commit();
            }
        }

        public void Remove(DayNameRecord dayname)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(dayname);
                transaction.Commit();
            }
        }

        public DayNameRecord GetById(long daynameId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<DayNameRecord>("ID = {0}", daynameId);
        }

        public DayNameRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<DayNameRecord>("Name = {0}", name);
            }
        }

        public ICollection<DayNameRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<DayNameRecord>();
            }
        }
    }
}