// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="DoorRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the Doors table.</summary>
    public partial class DoorRepository : IDoorRepository
    {
        public void Add(DoorRecord door)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(door);
                transaction.Commit();
            }
        }

        public void Update(DoorRecord door)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(door);
                transaction.Commit();
            }
        }

        public void Remove(DoorRecord door)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(door);
                transaction.Commit();
            }
        }

        public DoorRecord GetById(long doorId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<DoorRecord>("ID = {0}", doorId);
        }

        public DoorRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<DoorRecord>("Name = {0}", name);
            }
        }

        public ICollection<DoorRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<DoorRecord>();
            }
        }
    }
}