// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="DoorSideRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the DoorSides table.</summary>
    public partial class DoorSideRepository : IDoorSideRepository
    {
        public void Add(DoorSideRecord doorside)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(doorside);
                transaction.Commit();
            }
        }

        public void Update(DoorSideRecord doorside)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(doorside);
                transaction.Commit();
            }
        }

        public void Remove(DoorSideRecord doorside)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(doorside);
                transaction.Commit();
            }
        }

        public DoorSideRecord GetById(long doorsideId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<DoorSideRecord>("ID = {0}", doorsideId);
        }

        public DoorSideRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<DoorSideRecord>("Name = {0}", name);
            }
        }

        public ICollection<DoorSideRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<DoorSideRecord>();
            }
        }
    }
}