// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="ExitRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the Exits table.</summary>
    public partial class ExitRepository : IExitRepository
    {
        public void Add(ExitRecord exit)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(exit);
                transaction.Commit();
            }
        }

        public void Update(ExitRecord exit)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(exit);
                transaction.Commit();
            }
        }

        public void Remove(ExitRecord exit)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(exit);
                transaction.Commit();
            }
        }

        public ExitRecord GetById(long exitId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<ExitRecord>("ID = {0}", exitId);
        }

        public ExitRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<ExitRecord>("Name = {0}", name);
            }
        }

        public ICollection<ExitRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<ExitRecord>();
            }
        }
    }
}