// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="HelpTopicAliasRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the HelpTopicAliases table.</summary>
    public partial class HelpTopicAliasRepository : IHelpTopicAliasRepository
    {
        public void Add(HelpTopicAliasRecord helptopicalias)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(helptopicalias);
                transaction.Commit();
            }
        }

        public void Update(HelpTopicAliasRecord helptopicalias)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(helptopicalias);
                transaction.Commit();
            }
        }

        public void Remove(HelpTopicAliasRecord helptopicalias)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(helptopicalias);
                transaction.Commit();
            }
        }

        public HelpTopicAliasRecord GetById(long helptopicaliasId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<HelpTopicAliasRecord>("ID = {0}", helptopicaliasId);
        }

        public HelpTopicAliasRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<HelpTopicAliasRecord>("Name = {0}", name);
            }
        }

        public ICollection<HelpTopicAliasRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<HelpTopicAliasRecord>();
            }
        }
    }
}