// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="IacRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the IAC table.</summary>
    public partial class IacRepository : IIacRepository
    {
        public void Add(IacRecord iac)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(iac);
                transaction.Commit();
            }
        }

        public void Update(IacRecord iac)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(iac);
                transaction.Commit();
            }
        }

        public void Remove(IacRecord iac)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(iac);
                transaction.Commit();
            }
        }

        public IacRecord GetById(long iacId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<IacRecord>("ID = {0}", iacId);
        }

        public IacRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<IacRecord>("Name = {0}", name);
            }
        }

        public ICollection<IacRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<IacRecord>();
            }
        }
    }
}