// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MobTypeRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the MobTypes table.</summary>
    public partial class MobTypeRepository : IMobTypeRepository
    {
        public void Add(MobTypeRecord mobtype)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(mobtype);
                transaction.Commit();
            }
        }

        public void Update(MobTypeRecord mobtype)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(mobtype);
                transaction.Commit();
            }
        }

        public void Remove(MobTypeRecord mobtype)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(mobtype);
                transaction.Commit();
            }
        }

        public MobTypeRecord GetById(long mobtypeId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<MobTypeRecord>("ID = {0}", mobtypeId);
        }

        public MobTypeRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<MobTypeRecord>("Name = {0}", name);
            }
        }

        public ICollection<MobTypeRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<MobTypeRecord>();
            }
        }
    }
}