// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MudChannelRoleRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the MudChannelRoles table.</summary>
    public partial class MudChannelRoleRepository : IMudChannelRoleRepository
    {
        public void Add(MudChannelRoleRecord mudchannelrole)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(mudchannelrole);
                transaction.Commit();
            }
        }

        public void Update(MudChannelRoleRecord mudchannelrole)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(mudchannelrole);
                transaction.Commit();
            }
        }

        public void Remove(MudChannelRoleRecord mudchannelrole)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(mudchannelrole);
                transaction.Commit();
            }
        }

        public MudChannelRoleRecord GetById(long mudchannelroleId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<MudChannelRoleRecord>("ID = {0}", mudchannelroleId);
        }

        public MudChannelRoleRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<MudChannelRoleRecord>("Name = {0}", name);
            }
        }

        public ICollection<MudChannelRoleRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<MudChannelRoleRecord>();
            }
        }
    }
}