// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MudChannelRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the MudChannels table.</summary>
    public partial class MudChannelRepository : IMudChannelRepository
    {
        public void Add(MudChannelRecord mudchannel)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(mudchannel);
                transaction.Commit();
            }
        }

        public void Update(MudChannelRecord mudchannel)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(mudchannel);
                transaction.Commit();
            }
        }

        public void Remove(MudChannelRecord mudchannel)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(mudchannel);
                transaction.Commit();
            }
        }

        public MudChannelRecord GetById(long mudchannelId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<MudChannelRecord>("ID = {0}", mudchannelId);
        }

        public MudChannelRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<MudChannelRecord>("Name = {0}", name);
            }
        }

        public ICollection<MudChannelRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<MudChannelRecord>();
            }
        }
    }
}