// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="MxpRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the MXP table.</summary>
    public partial class MxpRepository : IMxpRepository
    {
        public void Add(MxpRecord mxp)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(mxp);
                transaction.Commit();
            }
        }

        public void Update(MxpRecord mxp)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(mxp);
                transaction.Commit();
            }
        }

        public void Remove(MxpRecord mxp)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(mxp);
                transaction.Commit();
            }
        }

        public MxpRecord GetById(long mxpId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<MxpRecord>("ID = {0}", mxpId);
        }

        public MxpRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<MxpRecord>("Name = {0}", name);
            }
        }

        public ICollection<MxpRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<MxpRecord>();
            }
        }
    }
}