// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="PlayerChannelRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the PlayerChannels table.</summary>
    public partial class PlayerChannelRepository : IPlayerChannelRepository
    {
        public void Add(PlayerChannelRecord playerchannel)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(playerchannel);
                transaction.Commit();
            }
        }

        public void Update(PlayerChannelRecord playerchannel)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(playerchannel);
                transaction.Commit();
            }
        }

        public void Remove(PlayerChannelRecord playerchannel)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(playerchannel);
                transaction.Commit();
            }
        }

        public PlayerChannelRecord GetById(long playerchannelId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<PlayerChannelRecord>("ID = {0}", playerchannelId);
        }

        public PlayerChannelRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<PlayerChannelRecord>("Name = {0}", name);
            }
        }

        public ICollection<PlayerChannelRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<PlayerChannelRecord>();
            }
        }
    }
}