// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="PortalExitRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the PortalExits table.</summary>
    public partial class PortalExitRepository : IPortalExitRepository
    {
        public void Add(PortalExitRecord portalexit)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(portalexit);
                transaction.Commit();
            }
        }

        public void Update(PortalExitRecord portalexit)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(portalexit);
                transaction.Commit();
            }
        }

        public void Remove(PortalExitRecord portalexit)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(portalexit);
                transaction.Commit();
            }
        }

        public PortalExitRecord GetById(long portalexitId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<PortalExitRecord>("ID = {0}", portalexitId);
        }

        public PortalExitRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<PortalExitRecord>("Name = {0}", name);
            }
        }

        public ICollection<PortalExitRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<PortalExitRecord>();
            }
        }
    }
}