// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="RoomTypeRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the RoomTypes table.</summary>
    public partial class RoomTypeRepository : IRoomTypeRepository
    {
        public void Add(RoomTypeRecord roomtype)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(roomtype);
                transaction.Commit();
            }
        }

        public void Update(RoomTypeRecord roomtype)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(roomtype);
                transaction.Commit();
            }
        }

        public void Remove(RoomTypeRecord roomtype)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(roomtype);
                transaction.Commit();
            }
        }

        public RoomTypeRecord GetById(long roomtypeId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<RoomTypeRecord>("ID = {0}", roomtypeId);
        }

        public RoomTypeRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<RoomTypeRecord>("Name = {0}", name);
            }
        }

        public ICollection<RoomTypeRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<RoomTypeRecord>();
            }
        }
    }
}