// <auto-generated />
//-----------------------------------------------------------------------------
// <copyright file="TypoRepository.cs" company="WheelMUD Development Team">
//   Copyright (c) WheelMUD Development Team. See LICENSE.txt. This file is
//   subject to the Microsoft Public License. All other rights reserved.
// </copyright>
// <summary>
//   auto-generated by Repository.cst on 4/9/2013 4:29:50 PM
// </summary>
//-----------------------------------------------------------------------------

namespace WheelMUD.Data.Repositories
{
    using System.Collections.Generic;
    using System.Data;
    using ServiceStack.OrmLite;
    using WheelMUD.Data.Entities;

    /// <summary>Repository for the Typos table.</summary>
    public partial class TypoRepository : ITypoRepository
    {
        public void Add(TypoRecord typo)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Save(typo);
                transaction.Commit();
            }
        }

        public void Update(TypoRecord typo)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Update(typo);
                transaction.Commit();
            }
        }

        public void Remove(TypoRecord typo)
        {
            using (IDbCommand session = Helpers.OpenSession())
            using (IDbTransaction transaction = session.Connection.BeginTransaction())
            {
                session.Connection.Delete(typo);
                transaction.Commit();
            }
        }

        public TypoRecord GetById(long typoId)
        {
            using (IDbCommand session = Helpers.OpenSession())
                return session.Connection.SingleWhere<TypoRecord>("ID = {0}", typoId);
        }

        public TypoRecord GetByName(string name)
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.SingleWhere<TypoRecord>("Name = {0}", name);
            }
        }

        public ICollection<TypoRecord> FetchAll()
        {
            using (IDbCommand session = Helpers.OpenSession())
            {
                return session.Connection.Select<TypoRecord>();
            }
        }
    }
}